const baseDatos = {
    "LÁCTEOS": {
        "Leche condensada": {
            "medida_casera": "1 cucharada",
            "medida": 10.0,
            "unidad": "g",
            "calorias": 32.8,
            "hc": 5.6,
            "proteinas": 0.8,
            "grasas": 0.8,
            "na": 9.0,
            "k": null,
            "p": 23.0,
            "ca": 28.4,
            "fe": null,
            "colest": 2.9,
            "purinas": 0.0,
            "fibra": null,
            "agua": 2.7,
            "afolic": null
        },
        "Leche descremada fluida Trébol": {
            "medida_casera": "1 taza",
            "medida": 200.0,
            "unidad": "ml",
            "calorias": 81.8,
            "hc": 10.8,
            "proteinas": 7.4,
            "grasas": 1.0,
            "na": 104.0,
            "k": 310.0,
            "p": 176.0,
            "ca": 230.0,
            "fe": null,
            "colest": 6.0,
            "purinas": 0.0,
            "fibra": null,
            "agua": 178.0,
            "afolic": null
        },
        "Leche descremada Mólico en polvo": {
            "medida_casera": "1 cucharada",
            "medida": 5.0,
            "unidad": "g",
            "calorias": 18.5,
            "hc": 2.6,
            "proteinas": 1.8,
            "grasas": 0.1,
            "na": null,
            "k": null,
            "p": 51.5,
            "ca": 64.5,
            "fe": 0.1,
            "colest": 0.1,
            "purinas": 0.0,
            "fibra": null,
            "agua": 0.2,
            "afolic": null
        },
        "Leche entera fluida": {
            "medida_casera": "1 taza",
            "medida": 200.0,
            "unidad": "ml",
            "calorias": 118.8,
            "hc": 9.6,
            "proteinas": 6.6,
            "grasas": 6.0,
            "na": 64.0,
            "k": 286.0,
            "p": 160.0,
            "ca": 220.0,
            "fe": null,
            "colest": 24.6,
            "purinas": 0.0,
            "fibra": null,
            "agua": 178.0,
            "afolic": null
        },
        "Leche entera calcio plus Trebol": {
            "medida_casera": "1 taza",
            "medida": 200.0,
            "unidad": "ml",
            "calorias": 90.0,
            "hc": 9.4,
            "proteinas": 6.4,
            "grasas": 3.0,
            "na": 116.0,
            "k": 0.0,
            "p": 210.0,
            "ca": 350.0,
            "fe": 0.0,
            "colest": 0.0,
            "purinas": 0.0,
            "fibra": 0.0,
            "agua": 0.0,
            "afolic": 0.0
        },
        "Leche entera Nido en polvo": {
            "medida_casera": "1 cucharada",
            "medida": 5.0,
            "unidad": "g",
            "calorias": 24.5,
            "hc": 1.9,
            "proteinas": 1.3,
            "grasas": 1.3,
            "na": 46.5,
            "k": null,
            "p": 37.5,
            "ca": 46.5,
            "fe": 37.5,
            "colest": 4.8,
            "purinas": 0.0,
            "fibra": null,
            "agua": 0.2,
            "afolic": null
        },
        "Queso Paraguay fresco": {
            "medida_casera": "1 porc chica",
            "medida": 50.0,
            "unidad": "g",
            "calorias": 110.5,
            "hc": 0.0,
            "proteinas": 8.5,
            "grasas": 8.5,
            "na": 42.5,
            "k": 262.5,
            "p": null,
            "ca": 100.0,
            "fe": 0.2,
            "colest": 48.5,
            "purinas": 0.0,
            "fibra": null,
            "agua": 33.0,
            "afolic": null
        },
        "Queso ricotta descremado": {
            "medida_casera": "1 cucharada",
            "medida": 20.0,
            "unidad": "g",
            "calorias": 27.6,
            "hc": 1.0,
            "proteinas": 2.3,
            "grasas": 1.6,
            "na": 2.5,
            "k": 25.0,
            "p": null,
            "ca": 54.4,
            "fe": 0.1,
            "colest": 18.0,
            "purinas": 0.0,
            "fibra": null,
            "agua": 14.0,
            "afolic": null
        },
        "Queso ricotta entero": {
            "medida_casera": "1 cucharada",
            "medida": 20.0,
            "unidad": "g",
            "calorias": 35.0,
            "hc": 0.6,
            "proteinas": 2.3,
            "grasas": 2.6,
            "na": 16.8,
            "k": 21.0,
            "p": null,
            "ca": 41.4,
            "fe": 1.0,
            "colest": 34.0,
            "purinas": 0.0,
            "fibra": null,
            "agua": 14.0,
            "afolic": null
        },
        "Queso sándwich": {
            "medida_casera": "1 feta",
            "medida": 30.0,
            "unidad": "g",
            "calorias": 67.8,
            "hc": 0.6,
            "proteinas": 4.9,
            "grasas": 5.1,
            "na": 21.0,
            "k": null,
            "p": 101.1,
            "ca": 210.0,
            "fe": 0.2,
            "colest": 18.0,
            "purinas": 0.0,
            "fibra": null,
            "agua": 17.7,
            "afolic": null
        },
        "Queso rallado": {
            "medida_casera": "1 cucharada",
            "medida": 10.0,
            "unidad": "g",
            "calorias": 35.7,
            "hc": 0.1,
            "proteinas": 3.2,
            "grasas": 2.5,
            "na": 117.0,
            "k": null,
            "p": 69.0,
            "ca": 117.0,
            "fe": null,
            "colest": 9.1,
            "purinas": 0.0,
            "fibra": null,
            "agua": 3.0,
            "afolic": null
        },
        "Yogur Bio Body con fibra": {
            "medida_casera": "1 pote",
            "medida": 180.0,
            "unidad": "g",
            "calorias": 64.0,
            "hc": 9.2,
            "proteinas": 6.8,
            "grasas": 0.0,
            "na": 85.5,
            "k": 0.0,
            "p": 126.0,
            "ca": 207.0,
            "fe": 0.0,
            "colest": 0.0,
            "purinas": 0.0,
            "fibra": 5.4,
            "agua": 0.0,
            "afolic": 0.0
        },
        "Yogur dietético (Lactolanda)": {
            "medida_casera": "1 pote chico",
            "medida": 140.0,
            "unidad": "g",
            "calorias": 56.3,
            "hc": 7.9,
            "proteinas": 4.6,
            "grasas": 0.7,
            "na": 85.4,
            "k": null,
            "p": 137.2,
            "ca": 140.0,
            "fe": null,
            "colest": 6.4,
            "purinas": 0.0,
            "fibra": null,
            "agua": 107.8,
            "afolic": null
        },
        "Yogur entero (Trebolín)": {
            "medida_casera": "1 pote chico",
            "medida": 140.0,
            "unidad": "g",
            "calorias": 138.3,
            "hc": 20.6,
            "proteinas": 5.9,
            "grasas": 3.6,
            "na": 98.0,
            "k": null,
            "p": 123.0,
            "ca": 145.0,
            "fe": null,
            "colest": 17.1,
            "purinas": 0.0,
            "fibra": null,
            "agua": 107.8,
            "afolic": null
        },
        "Yogur entero (Parmalat bebible)": {
            "medida_casera": "1 pote chico",
            "medida": 140.0,
            "unidad": "g",
            "calorias": 129.1,
            "hc": 19.6,
            "proteinas": 4.8,
            "grasas": 3.5,
            "na": 98.0,
            "k": null,
            "p": 131.6,
            "ca": 145.0,
            "fe": null,
            "colest": 17.0,
            "purinas": 0.0,
            "fibra": null,
            "agua": 107.8,
            "afolic": null
        },
        "Yogur entero (Coop bebible)": {
            "medida_casera": "1 pote chico",
            "medida": 160.0,
            "unidad": "g",
            "calorias": 144.8,
            "hc": 20.8,
            "proteinas": 6.4,
            "grasas": 4.0,
            "na": 112.0,
            "k": null,
            "p": 150.4,
            "ca": 167.0,
            "fe": null,
            "colest": 19.5,
            "purinas": 0.0,
            "fibra": null,
            "agua": 123.2,
            "afolic": null
        }
    },
    "HUEVOS": {
        "Clara de huevo": {
            "medida_casera": "1 mediana",
            "medida": 35.0,
            "unidad": "g",
            "calorias": 18.1,
            "hc": 0.4,
            "proteinas": 3.9,
            "grasas": 0.1,
            "na": 38.5,
            "k": 35.0,
            "p": 7.0,
            "ca": 3.2,
            "fe": 0.3,
            "colest": null,
            "purinas": 0.0,
            "fibra": null,
            "agua": 30.4,
            "afolic": null
        },
        "Huevo entero": {
            "medida_casera": "1 mediano",
            "medida": 70.0,
            "unidad": "g",
            "calorias": 101.7,
            "hc": 2.0,
            "proteinas": 7.9,
            "grasas": 6.9,
            "na": 56.7,
            "k": 70.0,
            "p": 142.8,
            "ca": 37.8,
            "fe": 1.7,
            "colest": 277.2,
            "purinas": 0.0,
            "fibra": null,
            "agua": 52.5,
            "afolic": null
        },
        "Huevo de codorniz": {
            "medida_casera": "1 unidad",
            "medida": 5.0,
            "unidad": "g",
            "calorias": 9.5,
            "hc": 0.2,
            "proteinas": 0.6,
            "grasas": 0.7,
            "na": null,
            "k": null,
            "p": 10.1,
            "ca": 3.7,
            "fe": 0.2,
            "colest": 21.5,
            "purinas": 0.0,
            "fibra": null,
            "agua": 3.5,
            "afolic": null
        }
    },
    "CARNE - AVES": {
        "Pollo (sin hueso ni piel)": {
            "medida_casera": "¼ pechuga",
            "medida": 90.0,
            "unidad": "g",
            "calorias": 80.5,
            "hc": 0.0,
            "proteinas": 17.2,
            "grasas": 1.3,
            "na": 70.2,
            "k": 288.0,
            "p": 213.3,
            "ca": 4.5,
            "fe": 0.9,
            "colest": 52.2,
            "purinas": 148.5,
            "fibra": null,
            "agua": 70.2,
            "afolic": null
        },
        "Pechuga de pollo picada": {
            "medida_casera": "1 cucharada",
            "medida": 20.0,
            "unidad": "g",
            "calorias": 17.9,
            "hc": 0.0,
            "proteinas": 3.8,
            "grasas": 0.3,
            "na": 15.6,
            "k": 64.0,
            "p": 47.4,
            "ca": 1.0,
            "fe": 0.2,
            "colest": 11.6,
            "purinas": 33.0,
            "fibra": null,
            "agua": 15.6,
            "afolic": null
        }
    },
    "CARNE - VACUNA": {
        "Bife magro": {
            "medida_casera": "1 grande",
            "medida": 200.0,
            "unidad": "g",
            "calorias": 294.0,
            "hc": 0.0,
            "proteinas": 42.0,
            "grasas": 14.0,
            "na": 94.0,
            "k": 736.0,
            "p": 468.0,
            "ca": 4.0,
            "fe": 6.4,
            "colest": 120.0,
            "purinas": 266.0,
            "fibra": null,
            "agua": 148.0,
            "afolic": null
        },
        "Carne molida de 1ª": {
            "medida_casera": "1 cucharada",
            "medida": 40.0,
            "unidad": "g",
            "calorias": 61.0,
            "hc": 0.0,
            "proteinas": 8.5,
            "grasas": 3.0,
            "na": 28.0,
            "k": 143.2,
            "p": 80.4,
            "ca": 0.8,
            "fe": 0.9,
            "colest": 36.0,
            "purinas": 53.2,
            "fibra": null,
            "agua": 26.8,
            "afolic": null
        },
        "Hígado (bife)": {
            "medida_casera": "1 chico chico",
            "medida": 100.0,
            "unidad": "g",
            "calorias": 128.7,
            "hc": 3.6,
            "proteinas": 19.8,
            "grasas": 3.9,
            "na": 110.0,
            "k": 380.0,
            "p": 278.0,
            "ca": 8.0,
            "fe": 5.1,
            "colest": 354.0,
            "purinas": 460.0,
            "fibra": null,
            "agua": 71.0,
            "afolic": null
        }
    },
    "CARNE - PESCADO": {
        "Atún enlatado al agua": {
            "medida_casera": "1 cucharada",
            "medida": 20.0,
            "unidad": "g",
            "calorias": 24.2,
            "hc": 0.0,
            "proteinas": 5.6,
            "grasas": 0.2,
            "na": 175.0,
            "k": 55.0,
            "p": 38.0,
            "ca": 3.2,
            "fe": 0.3,
            "colest": 5.6,
            "purinas": 51.4,
            "fibra": null,
            "agua": 14.0,
            "afolic": null
        },
        "Merluza": {
            "medida_casera": "1 filet chico",
            "medida": 100.0,
            "unidad": "g",
            "calorias": 84.4,
            "hc": 0.0,
            "proteinas": 19.3,
            "grasas": 0.8,
            "na": 61.0,
            "k": 304.0,
            "p": 318.0,
            "ca": 30.0,
            "fe": 1.1,
            "colest": 56.0,
            "purinas": 139.0,
            "fibra": null,
            "agua": 79.0,
            "afolic": null
        },
        "Surubí": {
            "medida_casera": "1 filet chico",
            "medida": 150.0,
            "unidad": "g",
            "calorias": 163.2,
            "hc": 0.0,
            "proteinas": 27.3,
            "grasas": 6.0,
            "na": 108.0,
            "k": 414.0,
            "p": 304.5,
            "ca": 30.0,
            "fe": 2.9,
            "colest": 78.0,
            "purinas": 210.0,
            "fibra": null,
            "agua": 115.5,
            "afolic": null
        }
    },
    "VEGETALES A": {
        "Acelga cruda": {
            "medida_casera": "1 taza",
            "medida": 90.0,
            "unidad": "g",
            "calorias": 30.0,
            "hc": 5.1,
            "proteinas": 1.5,
            "grasas": 0.4,
            "na": 189.0,
            "k": 648.0,
            "p": 27.0,
            "ca": 99.0,
            "fe": 3.0,
            "colest": null,
            "purinas": null,
            "fibra": 0.9,
            "agua": 81.9,
            "afolic": null
        },
        "Berro": {
            "medida_casera": "1 taza (té)",
            "medida": 70.0,
            "unidad": "g",
            "calorias": 19.9,
            "hc": 2.3,
            "proteinas": 2.0,
            "grasas": 0.3,
            "na": 36.4,
            "k": 239.4,
            "p": 53.2,
            "ca": 81.9,
            "fe": 1.3,
            "colest": null,
            "purinas": null,
            "fibra": 0.8,
            "agua": 64.4,
            "afolic": null
        },
        "Berenjena cruda": {
            "medida_casera": "1 taza grande",
            "medida": 200.0,
            "unidad": "g",
            "calorias": 63.8,
            "hc": 12.6,
            "proteinas": 2.0,
            "grasas": 0.6,
            "na": 2.0,
            "k": 380.0,
            "p": 62.0,
            "ca": 46.0,
            "fe": 1.6,
            "colest": null,
            "purinas": 2.0,
            "fibra": 2.4,
            "agua": 184.0,
            "afolic": null
        },
        "Brócoli": {
            "medida_casera": "1 taza (té)",
            "medida": 100.0,
            "unidad": "g",
            "calorias": 49.0,
            "hc": 6.4,
            "proteinas": 4.5,
            "grasas": 0.6,
            "na": 16.0,
            "k": 400.0,
            "p": 81.0,
            "ca": 116.0,
            "fe": 1.3,
            "colest": null,
            "purinas": 40.0,
            "fibra": 1.6,
            "agua": 87.0,
            "afolic": null
        },
        "Brote de soja": {
            "medida_casera": "1 taza",
            "medida": 100.0,
            "unidad": "g",
            "calorias": 37.5,
            "hc": 4.7,
            "proteinas": 5.5,
            "grasas": 1.0,
            "na": 30.0,
            "k": 235.0,
            "p": 74.6,
            "ca": 32.0,
            "fe": 0.9,
            "colest": 0.0,
            "purinas": 0.0,
            "fibra": 2.4,
            "agua": 0.0,
            "afolic": null
        },
        "Coliflor": {
            "medida_casera": "1 taza (té)",
            "medida": 100.0,
            "unidad": "g",
            "calorias": 40.8,
            "hc": 6.5,
            "proteinas": 2.8,
            "grasas": 0.4,
            "na": 24.0,
            "k": 400.0,
            "p": 58.0,
            "ca": 33.0,
            "fe": 1.0,
            "colest": null,
            "purinas": 25.0,
            "fibra": 1.0,
            "agua": 89.0,
            "afolic": null
        },
        "Espinaca": {
            "medida_casera": "1 mazo",
            "medida": 15.0,
            "unidad": "g",
            "calorias": 5.3,
            "hc": 0.7,
            "proteinas": 0.4,
            "grasas": 0.1,
            "na": 12.2,
            "k": 117.0,
            "p": 4.5,
            "ca": 9.0,
            "fe": 0.5,
            "colest": null,
            "purinas": 4.1,
            "fibra": 0.1,
            "agua": 13.5,
            "afolic": null
        },
        "Lechuga": {
            "medida_casera": "1 plato chico",
            "medida": 50.0,
            "unidad": "g",
            "calorias": 9.7,
            "hc": 1.5,
            "proteinas": 0.7,
            "grasas": 0.1,
            "na": 5.0,
            "k": 82.5,
            "p": 17.0,
            "ca": 21.5,
            "fe": 0.7,
            "colest": null,
            "purinas": 10.0,
            "fibra": 0.4,
            "agua": 47.5,
            "afolic": null
        },
        "Pepino": {
            "medida_casera": "½ taza (té)",
            "medida": 50.0,
            "unidad": "g",
            "calorias": 8.9,
            "hc": 1.7,
            "proteinas": 0.4,
            "grasas": 0.1,
            "na": 0.5,
            "k": 115.0,
            "p": 12.0,
            "ca": 8.0,
            "fe": 0.3,
            "colest": null,
            "purinas": 4.0,
            "fibra": 0.2,
            "agua": 47.5,
            "afolic": null
        },
        "Tomate perita (con semillas)": {
            "medida_casera": "1 chico",
            "medida": 100.0,
            "unidad": "g",
            "calorias": 24.3,
            "hc": 4.6,
            "proteinas": 0.8,
            "grasas": 0.3,
            "na": 3.0,
            "k": 230.0,
            "p": 24.0,
            "ca": 7.0,
            "fe": 0.6,
            "colest": null,
            "purinas": 10.0,
            "fibra": 0.6,
            "agua": 94.0,
            "afolic": null
        },
        "Tomate (con semillas)": {
            "medida_casera": "1 grande",
            "medida": 200.0,
            "unidad": "g",
            "calorias": 48.6,
            "hc": 9.2,
            "proteinas": 1.6,
            "grasas": 0.6,
            "na": 6.0,
            "k": 460.0,
            "p": 48.0,
            "ca": 14.0,
            "fe": 1.2,
            "colest": null,
            "purinas": 20.0,
            "fibra": 1.2,
            "agua": 188.0,
            "afolic": null
        }
    },
    "VEGETALES B": {
        "Arveja enlatada": {
            "medida_casera": "1 cucharada",
            "medida": 25.0,
            "unidad": "g",
            "calorias": 19.3,
            "hc": 4.4,
            "proteinas": 0.2,
            "grasas": 0.1,
            "na": 72.8,
            "k": 72.8,
            "p": 4.3,
            "ca": 2.3,
            "fe": 0.4,
            "colest": null,
            "purinas": 21.0,
            "fibra": 0.4,
            "agua": 21.8,
            "afolic": null
        },
        "Arveja natural cocida": {
            "medida_casera": "1 cucharada",
            "medida": 25.0,
            "unidad": "g",
            "calorias": 29.7,
            "hc": 5.3,
            "proteinas": 1.9,
            "grasas": 0.1,
            "na": 0.5,
            "k": 79.0,
            "p": 31.0,
            "ca": 6.0,
            "fe": 0.5,
            "colest": null,
            "purinas": 11.8,
            "fibra": 0.8,
            "agua": 17.5,
            "afolic": null
        },
        "Calabaza": {
            "medida_casera": "1 taza (té)",
            "medida": 100.0,
            "unidad": "g",
            "calorias": 34.6,
            "hc": 7.6,
            "proteinas": 0.6,
            "grasas": 0.2,
            "na": 1.0,
            "k": 260.0,
            "p": 22.0,
            "ca": 19.0,
            "fe": 0.5,
            "colest": null,
            "purinas": null,
            "fibra": 0.7,
            "agua": 91.0,
            "afolic": null
        }
    },
    "VEGETALES C": {
        "Choclo enlatado": {
            "medida_casera": "1 cucharada",
            "medida": 20.0,
            "unidad": "g",
            "calorias": 14.5,
            "hc": 3.0,
            "proteinas": 0.4,
            "grasas": 0.1,
            "na": 62.7,
            "k": 41.8,
            "p": 14.0,
            "ca": 0.6,
            "fe": 0.1,
            "colest": null,
            "purinas": 7.4,
            "fibra": 0.1,
            "agua": 16.4,
            "afolic": null
        },
        "Choclo natural": {
            "medida_casera": "1 cucharada",
            "medida": 20.0,
            "unidad": "g",
            "calorias": 22.6,
            "hc": 4.4,
            "proteinas": 0.8,
            "grasas": 0.2,
            "na": 0.2,
            "k": 74.0,
            "p": 0.4,
            "ca": 1.6,
            "fe": 0.2,
            "colest": null,
            "purinas": 7.4,
            "fibra": 0.2,
            "agua": 14.6,
            "afolic": null
        },
        "Papa": {
            "medida_casera": "1 pequeña",
            "medida": 100.0,
            "unidad": "g",
            "calorias": 79.7,
            "hc": 17.9,
            "proteinas": 1.8,
            "grasas": 0.1,
            "na": 1.0,
            "k": 410.0,
            "p": 40.0,
            "ca": 6.0,
            "fe": 0.8,
            "colest": null,
            "purinas": 5.0,
            "fibra": 0.4,
            "agua": 79.0,
            "afolic": null
        }
    },
    "FRUTAS A": {
        "Frutilla": {
            "medida_casera": "1 taza (té)",
            "medida": 100.0,
            "unidad": "g",
            "calorias": 39.9,
            "hc": 8.5,
            "proteinas": 0.8,
            "grasas": 0.3,
            "na": 1.0,
            "k": 180.0,
            "p": 29.8,
            "ca": 29.0,
            "fe": 1.0,
            "colest": null,
            "purinas": 12.0,
            "fibra": 1.3,
            "agua": 90.0,
            "afolic": null
        },
        "Mandarina": {
            "medida_casera": "1 grande",
            "medida": 150.0,
            "unidad": "g",
            "calorias": 72.7,
            "hc": 16.4,
            "proteinas": 1.1,
            "grasas": 0.3,
            "na": 3.0,
            "k": 165.0,
            "p": 24.0,
            "ca": 45.0,
            "fe": 0.6,
            "colest": null,
            "purinas": 0.0,
            "fibra": 0.6,
            "agua": 132.0,
            "afolic": null
        },
        "Melón": {
            "medida_casera": "1 rodaja",
            "medida": 100.0,
            "unidad": "g",
            "calorias": 27.7,
            "hc": 6.2,
            "proteinas": 0.5,
            "grasas": 0.1,
            "na": 12.0,
            "k": 230.0,
            "p": 15.0,
            "ca": 15.0,
            "fe": 1.2,
            "colest": null,
            "purinas": 0.0,
            "fibra": 0.5,
            "agua": 93.0,
            "afolic": null
        },
        "Naranja": {
            "medida_casera": "1 mediana",
            "medida": 150.0,
            "unidad": "g",
            "calorias": 70.7,
            "hc": 15.8,
            "proteinas": 1.2,
            "grasas": 0.3,
            "na": 1.5,
            "k": 255.0,
            "p": 30.0,
            "ca": 51.0,
            "fe": 1.5,
            "colest": null,
            "purinas": 0.0,
            "fibra": 0.6,
            "agua": 132.0,
            "afolic": null
        },
        "Naranja (jugo puro)": {
            "medida_casera": "1 vaso",
            "medida": 250.0,
            "unidad": "ml",
            "calorias": 117.7,
            "hc": 26.3,
            "proteinas": 2.0,
            "grasas": 0.5,
            "na": 2.5,
            "k": 410.0,
            "p": 40.0,
            "ca": 85.0,
            "fe": 0.8,
            "colest": null,
            "purinas": 0.0,
            "fibra": 1.0,
            "agua": 218.0,
            "afolic": null
        },
        "Pomelo": {
            "medida_casera": "1 grande",
            "medida": 190.0,
            "unidad": "g",
            "calorias": 80.8,
            "hc": 18.2,
            "proteinas": 1.1,
            "grasas": 0.4,
            "na": 1.9,
            "k": 380.0,
            "p": 39.9,
            "ca": 34.2,
            "fe": 10.0,
            "colest": null,
            "purinas": 0.0,
            "fibra": 0.4,
            "agua": 169.1,
            "afolic": null
        }
    },
    "FRUTAS B": {
        "Ciruela": {
            "medida_casera": "1 chica",
            "medida": 60.0,
            "unidad": "g",
            "calorias": 30.9,
            "hc": 7.1,
            "proteinas": 0.4,
            "grasas": 0.1,
            "na": 0.7,
            "k": 136.5,
            "p": 9.8,
            "ca": 4.8,
            "fe": 0.3,
            "colest": null,
            "purinas": 0.0,
            "fibra": 0.2,
            "agua": 56.5,
            "afolic": null
        },
        "Durazno natural": {
            "medida_casera": "1 unidad",
            "medida": 110.0,
            "unidad": "g",
            "calorias": 63.8,
            "hc": 14.6,
            "proteinas": 0.9,
            "grasas": 0.2,
            "na": 1.1,
            "k": 176.0,
            "p": 28.6,
            "ca": 13.2,
            "fe": 1.2,
            "colest": null,
            "purinas": 0.0,
            "fibra": 1.0,
            "agua": 93.5,
            "afolic": null
        },
        "Mamón": {
            "medida_casera": "½ chico",
            "medida": 150.0,
            "unidad": "g",
            "calorias": 129.1,
            "hc": 29.9,
            "proteinas": 1.7,
            "grasas": 0.3,
            "na": 10.7,
            "k": null,
            "p": 30.0,
            "ca": 18.0,
            "fe": 0.9,
            "colest": null,
            "purinas": 0.0,
            "fibra": 2.1,
            "agua": 117.0,
            "afolic": null
        },
        "Manzana": {
            "medida_casera": "1 mediana",
            "medida": 170.0,
            "unidad": "g",
            "calorias": 109.7,
            "hc": 25.8,
            "proteinas": 0.5,
            "grasas": 0.5,
            "na": 1.7,
            "k": 129.2,
            "p": 17.0,
            "ca": 10.2,
            "fe": 0.7,
            "colest": null,
            "purinas": 5.1,
            "fibra": 1.2,
            "agua": 142.8,
            "afolic": null
        },
        "Pera": {
            "medida_casera": "1 grande",
            "medida": 200.0,
            "unidad": "g",
            "calorias": 124.4,
            "hc": 29.6,
            "proteinas": 0.6,
            "grasas": 0.4,
            "na": 4.0,
            "k": 200.0,
            "p": 20.6,
            "ca": 12.0,
            "fe": 1.0,
            "colest": null,
            "purinas": 4.0,
            "fibra": 3.4,
            "agua": 168.0,
            "afolic": null
        },
        "Piña": {
            "medida_casera": "1 rodaja",
            "medida": 100.0,
            "unidad": "g",
            "calorias": 58.2,
            "hc": 13.7,
            "proteinas": 0.4,
            "grasas": 0.2,
            "na": 1.0,
            "k": 210.0,
            "p": 8.0,
            "ca": 18.0,
            "fe": 0.5,
            "colest": null,
            "purinas": 0.0,
            "fibra": 0.4,
            "agua": 85.0,
            "afolic": null
        }
    },
    "FRUTAS C": {
        "Banana": {
            "medida_casera": "1 mediana",
            "medida": 70.0,
            "unidad": "g",
            "calorias": 70.5,
            "hc": 16.6,
            "proteinas": 0.8,
            "grasas": 0.1,
            "na": 0.7,
            "k": 294.0,
            "p": 19.6,
            "ca": 7.0,
            "fe": 0.6,
            "colest": null,
            "purinas": 0.0,
            "fibra": 0.4,
            "agua": 51.8,
            "afolic": null
        }
    },
    "FRUTOS SECOS": {
        "Almendras": {
            "medida_casera": "1 cucharada",
            "medida": 10.0,
            "unidad": "g",
            "calorias": 64.2,
            "hc": 2.0,
            "proteinas": 1.9,
            "grasas": 5.4,
            "na": 0.3,
            "k": 6.9,
            "p": 4.8,
            "ca": 25.4,
            "fe": 0.4,
            "colest": null,
            "purinas": 3.0,
            "fibra": 0.3,
            "agua": 0.5,
            "afolic": null
        },
        "Maní molido": {
            "medida_casera": "1 cucharada",
            "medida": 10.0,
            "unidad": "g",
            "calorias": 60.3,
            "hc": 1.8,
            "proteinas": 2.7,
            "grasas": 4.7,
            "na": 0.5,
            "k": 6.8,
            "p": 4.7,
            "ca": 4.6,
            "fe": 0.3,
            "colest": null,
            "purinas": 9.0,
            "fibra": 0.2,
            "agua": 0.6,
            "afolic": null
        }
    },
    "CEREALES": {
        "Almidón de mandioca": {
            "medida_casera": "1 cucharada",
            "medida": 10.0,
            "unidad": "g",
            "calorias": 33.7,
            "hc": 8.1,
            "proteinas": 0.2,
            "grasas": 0.1,
            "na": 0.4,
            "k": 2.2,
            "p": 10.4,
            "ca": null,
            "fe": 0.5,
            "colest": null,
            "purinas": 0.0,
            "fibra": 0.2,
            "agua": 1.4,
            "afolic": null
        },
        "Arroz pulido": {
            "medida_casera": "1 cucharada",
            "medida": 15.0,
            "unidad": "g",
            "calorias": 53.3,
            "hc": 12.1,
            "proteinas": 1.0,
            "grasas": 0.1,
            "na": 0.8,
            "k": 13.8,
            "p": 14.1,
            "ca": 3.6,
            "fe": 0.1,
            "colest": null,
            "purinas": 0.0,
            "fibra": 0.1,
            "agua": 1.8,
            "afolic": null
        },
        "Arroz integral": {
            "medida_casera": "1 cucharada",
            "medida": 15.0,
            "unidad": "g",
            "calorias": 55.5,
            "hc": 12.1,
            "proteinas": 1.1,
            "grasas": 0.3,
            "na": 1.4,
            "k": 31.9,
            "p": 31.8,
            "ca": 2.1,
            "fe": 0.2,
            "colest": null,
            "purinas": 0.0,
            "fibra": 0.2,
            "agua": 1.8,
            "afolic": null
        },
        "Cereal All Bran": {
            "medida_casera": "1 cucharada",
            "medida": 5.0,
            "unidad": "g",
            "calorias": 17.7,
            "hc": 3.6,
            "proteinas": 0.6,
            "grasas": 0.1,
            "na": 51.3,
            "k": 74.6,
            "p": null,
            "ca": null,
            "fe": 1.1,
            "colest": null,
            "purinas": null,
            "fibra": null,
            "agua": null,
            "afolic": null
        },
        "Cereal Kellogs (cornflekes)": {
            "medida_casera": "1 cucharada",
            "medida": 5.0,
            "unidad": "g",
            "calorias": 18.0,
            "hc": 4.2,
            "proteinas": 0.3,
            "grasas": 0.0,
            "na": 55.0,
            "k": 5.9,
            "p": null,
            "ca": null,
            "fe": null,
            "colest": null,
            "purinas": null,
            "fibra": 0.2,
            "agua": null,
            "afolic": null
        }
    },
    "PANIFICADOS": {
        "Galleta": {
            "medida_casera": "1 mediana",
            "medida": 70.0,
            "unidad": "g",
            "calorias": 252.5,
            "hc": 53.0,
            "proteinas": 9.0,
            "grasas": 0.5,
            "na": 21.0,
            "k": 72.4,
            "p": 80.5,
            "ca": null,
            "fe": null,
            "colest": null,
            "purinas": null,
            "fibra": 0.2,
            "agua": 7.7,
            "afolic": null
        },
        "Galleta molida": {
            "medida_casera": "1 cucharada",
            "medida": 10.0,
            "unidad": "g",
            "calorias": 36.5,
            "hc": 7.6,
            "proteinas": 1.3,
            "grasas": 0.1,
            "na": 3.0,
            "k": null,
            "p": null,
            "ca": null,
            "fe": null,
            "colest": null,
            "purinas": null,
            "fibra": 0.0,
            "agua": 0.3,
            "afolic": null
        },
        "Galletita Cerealita": {
            "medida_casera": "1 unidad",
            "medida": 6.0,
            "unidad": "g",
            "calorias": 26.5,
            "hc": 4.0,
            "proteinas": 0.6,
            "grasas": 0.9,
            "na": 33.0,
            "k": null,
            "p": null,
            "ca": null,
            "fe": null,
            "colest": null,
            "purinas": null,
            "fibra": null,
            "agua": 0.2,
            "afolic": null
        },
        "Galletita Criollitas": {
            "medida_casera": "1 unidad",
            "medida": 7.0,
            "unidad": "g",
            "calorias": 29.5,
            "hc": 4.9,
            "proteinas": 0.9,
            "grasas": 0.7,
            "na": 38.3,
            "k": null,
            "p": null,
            "ca": null,
            "fe": null,
            "colest": null,
            "purinas": null,
            "fibra": null,
            "agua": 0.2,
            "afolic": null
        },
        "Galletita Criollitas mini": {
            "medida_casera": "1 unidad",
            "medida": 4.0,
            "unidad": "g",
            "calorias": 16.8,
            "hc": 2.8,
            "proteinas": 0.5,
            "grasas": 0.4,
            "na": 21.9,
            "k": null,
            "p": null,
            "ca": null,
            "fe": null,
            "colest": null,
            "purinas": null,
            "fibra": null,
            "agua": 0.1,
            "afolic": null
        },
        "Galletita Familiares de agua": {
            "medida_casera": "1 unidad",
            "medida": 7.0,
            "unidad": "g",
            "calorias": 29.6,
            "hc": 5.2,
            "proteinas": 0.8,
            "grasas": 0.6,
            "na": 44.9,
            "k": null,
            "p": 17.1,
            "ca": null,
            "fe": null,
            "colest": null,
            "purinas": null,
            "fibra": null,
            "agua": 0.2,
            "afolic": null
        },
        "Galletita Familiares integral": {
            "medida_casera": "1 unidad",
            "medida": 6.0,
            "unidad": "g",
            "calorias": 25.9,
            "hc": 4.1,
            "proteinas": 0.8,
            "grasas": 0.7,
            "na": 64.4,
            "k": null,
            "p": 19.2,
            "ca": 3.8,
            "fe": 0.1,
            "colest": null,
            "purinas": null,
            "fibra": 0.5,
            "agua": 0.2,
            "afolic": null
        },
        "Galletita Familiares salvado": {
            "medida_casera": "1 unidad",
            "medida": 6.0,
            "unidad": "g",
            "calorias": 25.0,
            "hc": 4.2,
            "proteinas": 0.7,
            "grasas": 0.6,
            "na": 71.1,
            "k": null,
            "p": null,
            "ca": null,
            "fe": null,
            "colest": null,
            "purinas": null,
            "fibra": null,
            "agua": 0.2,
            "afolic": null
        },
        "Galletita Sándwich sin sal": {
            "medida_casera": "1 unidad",
            "medida": 7.0,
            "unidad": "g",
            "calorias": 31.0,
            "hc": 4.8,
            "proteinas": 0.7,
            "grasas": 1.0,
            "na": 16.4,
            "k": null,
            "p": null,
            "ca": null,
            "fe": null,
            "colest": null,
            "purinas": null,
            "fibra": null,
            "agua": 0.2,
            "afolic": null
        },
        "Madalenas Bimbo": {
            "medida_casera": "1 unidad",
            "medida": 25.0,
            "unidad": "g",
            "calorias": 103.0,
            "hc": 13.0,
            "proteinas": 1.8,
            "grasas": 4.9,
            "na": 75.0,
            "k": 0.0,
            "p": 0.0,
            "ca": 0.0,
            "fe": 0.0,
            "colest": 0.0,
            "purinas": 19.0,
            "fibra": 0.0,
            "agua": 0.2,
            "afolic": 0.0
        },
        "Palito/rosquitas": {
            "medida_casera": "5 unidades",
            "medida": 50.0,
            "unidad": "g",
            "calorias": 171.1,
            "hc": 36.3,
            "proteinas": 6.3,
            "grasas": 0.1,
            "na": 324.0,
            "k": null,
            "p": null,
            "ca": null,
            "fe": null,
            "colest": null,
            "purinas": 0.0,
            "fibra": null,
            "agua": null,
            "afolic": null
        },
        "Rapiditas Clásicas Bimbo": {
            "medida_casera": "1 unidad",
            "medida": 30.0,
            "unidad": "g",
            "calorias": 81.6,
            "hc": 13.8,
            "proteinas": 1.8,
            "grasas": 2.1,
            "na": 130.8,
            "k": 0.0,
            "p": 0.0,
            "ca": 0.0,
            "fe": 0.0,
            "colest": 0.0,
            "purinas": 0.0,
            "fibra": 0.0,
            "agua": 0.6,
            "afolic": 0.0
        },
        "Rapiditas Light Bimbo": {
            "medida_casera": "1 unidad",
            "medida": 30.0,
            "unidad": "g",
            "calorias": 77.4,
            "hc": 13.8,
            "proteinas": 2.3,
            "grasas": 1.4,
            "na": 118.2,
            "k": 0.0,
            "p": 0.0,
            "ca": 0.0,
            "fe": 0.0,
            "colest": 0.0,
            "purinas": 0.0,
            "fibra": 0.0,
            "agua": 0.0,
            "afolic": null
        },
        "Pan Felipe (bollo)": {
            "medida_casera": "1 unidad",
            "medida": 50.0,
            "unidad": "g",
            "calorias": 134.5,
            "hc": 28.7,
            "proteinas": 4.7,
            "grasas": 0.1,
            "na": 137.0,
            "k": 46.5,
            "p": 53.5,
            "ca": null,
            "fe": 0.6,
            "colest": null,
            "purinas": 0.0,
            "fibra": 0.1,
            "agua": 15.5,
            "afolic": null
        },
        "Pan francés": {
            "medida_casera": "1 rebanada",
            "medida": 30.0,
            "unidad": "g",
            "calorias": 80.9,
            "hc": 17.2,
            "proteinas": 2.8,
            "grasas": 0.1,
            "na": 82.2,
            "k": 27.9,
            "p": 32.1,
            "ca": 6.6,
            "fe": 0.3,
            "colest": null,
            "purinas": 0.0,
            "fibra": 0.1,
            "agua": 9.3,
            "afolic": null
        },
        "Pan Sandwich Blanco": {
            "medida_casera": "1 unidad",
            "medida": 30.0,
            "unidad": "g",
            "calorias": 63.0,
            "hc": 13.2,
            "proteinas": 2.0,
            "grasas": 0.5,
            "na": 78.6,
            "k": 0.0,
            "p": 0.0,
            "ca": 0.0,
            "fe": 0.0,
            "colest": 0.0,
            "purinas": 0.0,
            "fibra": 0.4,
            "agua": 0.0,
            "afolic": 0.0
        },
        "Pan Sandwich Salvado": {
            "medida_casera": "1 unidad",
            "medida": 30.0,
            "unidad": "g",
            "calorias": 82.2,
            "hc": 15.3,
            "proteinas": 2.1,
            "grasas": 1.4,
            "na": 288.7,
            "k": 76.8,
            "p": 76.2,
            "ca": null,
            "fe": null,
            "colest": null,
            "purinas": 12.0,
            "fibra": 0.5,
            "agua": 10.8,
            "afolic": null
        },
        "Pan Viena": {
            "medida_casera": "1 unidad",
            "medida": 40.0,
            "unidad": "g",
            "calorias": 122.8,
            "hc": 25.0,
            "proteinas": 3.9,
            "grasas": 0.8,
            "na": 110.0,
            "k": null,
            "p": 62.8,
            "ca": 15.6,
            "fe": 0.3,
            "colest": null,
            "purinas": 0.0,
            "fibra": 0.1,
            "agua": 10.0,
            "afolic": null
        }
    },
    "DULCES": {
        "Azúcar blanca granulada": {
            "medida_casera": "1 cucharada",
            "medida": 10.0,
            "unidad": "g",
            "calorias": 40.0,
            "hc": 10.0,
            "proteinas": 0.0,
            "grasas": 0.0,
            "na": null,
            "k": null,
            "p": null,
            "ca": null,
            "fe": null,
            "colest": null,
            "purinas": 0.0,
            "fibra": null,
            "agua": null,
            "afolic": null
        },
        "Azúcar impalpable": {
            "medida_casera": "1 cucharada",
            "medida": 10.0,
            "unidad": "g",
            "calorias": 40.0,
            "hc": 10.0,
            "proteinas": 0.0,
            "grasas": 0.0,
            "na": 0.1,
            "k": 0.3,
            "p": null,
            "ca": null,
            "fe": null,
            "colest": null,
            "purinas": 0.0,
            "fibra": null,
            "agua": 0.1,
            "afolic": null
        },
        "Chocolate Nesquik (polvo)": {
            "medida_casera": "1 cucharada",
            "medida": 10.0,
            "unidad": "g",
            "calorias": 40.3,
            "hc": 8.9,
            "proteinas": 0.5,
            "grasas": 0.3,
            "na": null,
            "k": null,
            "p": null,
            "ca": null,
            "fe": null,
            "colest": null,
            "purinas": null,
            "fibra": null,
            "agua": null,
            "afolic": null
        },
        "Chocolate Nestlé (polvo)": {
            "medida_casera": "1 cucharada",
            "medida": 10.0,
            "unidad": "g",
            "calorias": 34.6,
            "hc": 6.0,
            "proteinas": 1.3,
            "grasas": 0.6,
            "na": null,
            "k": null,
            "p": null,
            "ca": null,
            "fe": 0.9,
            "colest": null,
            "purinas": null,
            "fibra": null,
            "agua": null,
            "afolic": null
        },
        "Dulce de batata": {
            "medida_casera": "1 porc chica",
            "medida": 50.0,
            "unidad": "g",
            "calorias": 127.9,
            "hc": 31.2,
            "proteinas": 0.1,
            "grasas": 0.3,
            "na": 28.4,
            "k": 31.9,
            "p": 3.9,
            "ca": 4.1,
            "fe": null,
            "colest": null,
            "purinas": null,
            "fibra": 0.6,
            "agua": 16.0,
            "afolic": null
        },
        "Dulce de leche": {
            "medida_casera": "1 cucharada",
            "medida": 20.0,
            "unidad": "g",
            "calorias": 72.2,
            "hc": 12.4,
            "proteinas": 1.6,
            "grasas": 1.8,
            "na": 24.4,
            "k": 78.6,
            "p": 51.4,
            "ca": 64.4,
            "fe": 0.1,
            "colest": null,
            "purinas": null,
            "fibra": null,
            "agua": 4.8,
            "afolic": null
        },
        "Dulce de membrillo": {
            "medida_casera": "1 porc chica",
            "medida": 50.0,
            "unidad": "g",
            "calorias": 177.4,
            "hc": 43.4,
            "proteinas": 0.5,
            "grasas": 0.2,
            "na": 32.3,
            "k": 73.7,
            "p": 5.2,
            "ca": 0.9,
            "fe": null,
            "colest": null,
            "purinas": null,
            "fibra": 0.4,
            "agua": 17.5,
            "afolic": null
        },
        "Gelatina dietética": {
            "medida_casera": "1 compotera",
            "medida": 100.0,
            "unidad": "g",
            "calorias": 8.0,
            "hc": 0.3,
            "proteinas": 1.7,
            "grasas": 0.0,
            "na": 109.0,
            "k": null,
            "p": null,
            "ca": null,
            "fe": null,
            "colest": null,
            "purinas": 0.0,
            "fibra": null,
            "agua": 97.1,
            "afolic": null
        },
        "Gelatina normal": {
            "medida_casera": "1 compotera",
            "medida": 100.0,
            "unidad": "g",
            "calorias": 55.2,
            "hc": 12.3,
            "proteinas": 1.5,
            "grasas": 0.0,
            "na": 51.0,
            "k": null,
            "p": null,
            "ca": null,
            "fe": null,
            "colest": null,
            "purinas": 0.0,
            "fibra": null,
            "agua": 83.1,
            "afolic": null
        },
        "Jugo Ades Manzana/naranja": {
            "medida_casera": "½ vaso",
            "medida": 100.0,
            "unidad": "ml",
            "calorias": 43.8,
            "hc": 10.0,
            "proteinas": 0.5,
            "grasas": 0.2,
            "na": 17.0,
            "k": 42.5,
            "p": 12.2,
            "ca": null,
            "fe": 0.2,
            "colest": null,
            "purinas": 0.0,
            "fibra": null,
            "agua": 90.0,
            "afolic": null
        },
        "Jugo Ades Natural": {
            "medida_casera": "½ vaso",
            "medida": 100.0,
            "unidad": "ml",
            "calorias": 38.9,
            "hc": 3.2,
            "proteinas": 2.7,
            "grasas": 1.7,
            "na": 67.3,
            "k": 163.8,
            "p": 46.9,
            "ca": null,
            "fe": 0.7,
            "colest": null,
            "purinas": 0.0,
            "fibra": null,
            "agua": 90.0,
            "afolic": null
        },
        "Mermelada": {
            "medida_casera": "1 cucharadita",
            "medida": 5.0,
            "unidad": "g",
            "calorias": 14.1,
            "hc": 3.5,
            "proteinas": 0.0,
            "grasas": 0.0,
            "na": 0.6,
            "k": 4.4,
            "p": 0.5,
            "ca": 1.0,
            "fe": 0.1,
            "colest": null,
            "purinas": 0.0,
            "fibra": 0.1,
            "agua": 1.4,
            "afolic": null
        },
        "Mermelada dietética": {
            "medida_casera": "1 cucharadita",
            "medida": 5.0,
            "unidad": "g",
            "calorias": 5.2,
            "hc": 1.3,
            "proteinas": 0.0,
            "grasas": 0.0,
            "na": null,
            "k": null,
            "p": null,
            "ca": null,
            "fe": null,
            "colest": null,
            "purinas": 0.0,
            "fibra": 0.0,
            "agua": 1.0,
            "afolic": null
        },
        "Miel de abeja": {
            "medida_casera": "1 cucharada",
            "medida": 5.0,
            "unidad": "g",
            "calorias": 15.6,
            "hc": 3.9,
            "proteinas": 0.0,
            "grasas": 0.0,
            "na": 0.4,
            "k": 0.5,
            "p": 0.8,
            "ca": 1.0,
            "fe": 0.0,
            "colest": null,
            "purinas": 0.0,
            "fibra": null,
            "agua": 1.1,
            "afolic": null
        },
        "Miel negra": {
            "medida_casera": "1 cucharada",
            "medida": 5.0,
            "unidad": "g",
            "calorias": 14.5,
            "hc": 3.6,
            "proteinas": 0.0,
            "grasas": 0.0,
            "na": null,
            "k": null,
            "p": 2.1,
            "ca": 3.5,
            "fe": 0.1,
            "colest": null,
            "purinas": 0.0,
            "fibra": 0.3,
            "agua": 1.3,
            "afolic": null
        }
    },
    "GRASAS": {
        "Aceite": {
            "medida_casera": "1 cucharada",
            "medida": 5.0,
            "unidad": "g",
            "calorias": 45.0,
            "hc": 0.0,
            "proteinas": 0.0,
            "grasas": 5.0,
            "na": 0.1,
            "k": 0.1,
            "p": null,
            "ca": 0.8,
            "fe": null,
            "colest": null,
            "purinas": 0.0,
            "fibra": null,
            "agua": null,
            "afolic": null
        },
        "Crema de leche (40%)": {
            "medida_casera": "1 cucharada",
            "medida": 10.0,
            "unidad": "g",
            "calorias": 36.2,
            "hc": 0.3,
            "proteinas": 0.2,
            "grasas": 3.8,
            "na": 3.2,
            "k": 8.9,
            "p": 5.9,
            "ca": 7.5,
            "fe": null,
            "colest": 136.0,
            "purinas": 0.0,
            "fibra": null,
            "agua": 5.7,
            "afolic": null
        },
        "Jamón cocido": {
            "medida_casera": "1 feta",
            "medida": 25.0,
            "unidad": "g",
            "calorias": 74.8,
            "hc": 0.5,
            "proteinas": 6.5,
            "grasas": 5.2,
            "na": 275.0,
            "k": 57.6,
            "p": 35.0,
            "ca": null,
            "fe": null,
            "colest": 21.3,
            "purinas": 10.8,
            "fibra": null,
            "agua": 10.0,
            "afolic": null
        },
        "Manteca": {
            "medida_casera": "1 cucharadita",
            "medida": 4.0,
            "unidad": "g",
            "calorias": 30.7,
            "hc": 0.0,
            "proteinas": 0.0,
            "grasas": 3.4,
            "na": 8.9,
            "k": 0.6,
            "p": 1.0,
            "ca": 0.6,
            "fe": null,
            "colest": 9.6,
            "purinas": 0.0,
            "fibra": null,
            "agua": 0.6,
            "afolic": null
        },
        "Margarina": {
            "medida_casera": "1 cucharadita",
            "medida": 4.0,
            "unidad": "g",
            "calorias": 27.0,
            "hc": 0.0,
            "proteinas": 0.0,
            "grasas": 3.0,
            "na": 4.0,
            "k": null,
            "p": null,
            "ca": null,
            "fe": null,
            "colest": 4.6,
            "purinas": 0.0,
            "fibra": null,
            "agua": null,
            "afolic": null
        }
    }
};
